if_show_working_info: false #那些运行中的info正常提示或者什么的,要不要显示

work_environment: 2     #雷达与惯性传感器工作环境配置，1为livox固态系列，2为仿真HDL-32线，3为镭神
##根据工作环境，分配话题



odom_end_send_tf: false    #参数默认false，决定odom_end是否广播tf
matching_end_send_tf: false #参数默认false，决定matching_end是否广播tf
optimizing_end_send_tf: false #参数默认false，决定optimizing_end是否广播tf

######## topic or frame part######## 配置传感器话题输入部分
global_frame_id_1: odom     ##不要有斜杠
imu_1: /livox/imu
imu_synced_1: /synced_imu
laser_pointcloud_1: /livox/lidar  #未去畸变原始点云
undistorted_pointcloud_1: /livox/lidar_pro #设定完成去畸变点云的发布话题
imu_link_1: laser_link
lidar_link_1: laser_link
car_base_link_1: laser_link                     #仿真车体连结点
init_position_1: [0.0,0.00,0.00]


global_frame_id_2: odom
imu_2: /imu
imu_synced_2: /synced_imu
laser_pointcloud_2: /velodyne_points2  #未去畸变原始点云
undistorted_pointcloud_2: /velodyne_points2_pro
imu_link_2: imu
lidar_link_2: velodyne2_base_link
car_base_link_2: base_link                     #仿真车体连结点
#初始，相对于点云pcd或者是gazebo仿真世界的位置
init_position_2: [5.00,2.00,0.00]



base_frame_id:  map                   ##不要有斜杠
########input_topic_part########



registration_method: NDT_CUDA # 里程计选择点云匹配方法 目前支持 ICP_SVD , ICP , NDT , NDT_CPU , SICP , NDT_CUDA
# b. 全局地图点云pcd文件路径:
map_path_1: /pcd_map/scans0221.pcd   # 使用时：WORK_PACKAGE_PATH + map_path
map_path_2: /pcd_map/2023rmus_full_scans.pcd


# 几个参数用于比较数据预处理部分的效果，只有数据预处理端调用
dedistortion_work: false   # 去自运动畸变使能
imu_sync_work:     true    # imu线性插值同步使能
filter_self_work:  true    # 去除机身自身点使能