/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 640 
      image_height: 360
      camera_name: "camera3"
      camera_info_url: "package://usb_cam/config/camera_info3.yaml"
