localization_record:
  - /livox/lidar
  - /livox/imu
#   - /tdt_localization_cheng
#   - /front_end_path
#   - /tdt_localization_linear

vision_bag_record:
  # - /armor_detection
  # - /vision_debug_info
  # - topic2
  # - topic3

# 设置 数据集文件夹 相对于本yaml文件所在文件夹的储存位置：path = "...src/databag_tool/" + bags_relative_path , 用于 record 和 merge
# bags_relative_path: ../../../ros2bags/   
bags_relative_path: bags/   


# 强制停止时间，单次开机自启或启动后的停止时间
forced_stop_time: 1500